### ISSUE TITLE
I get the following error for some reason.

### ISSUE THREAD

**Issue by Achisyg2** [AmrDeveloper/ReactButton#10]
**Describe the bug**
Everything else is working perfect. However, when I scroll faster on the recyclerview I get the following error:
`java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
        at com.app.selfcial.Adapters.PostsAdapter$7.onComplete(PostsAdapter.java:592)
        at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**To Reproduce**
1. Click on a reaction
2. Save it in Firebase with reaction id
3. setCurrentReaction based on the saved id
4. Scroll a bit bit faster the recyelerview

**Expected behavior**
It should work same as when scrolling slow

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 8
 - OS: Android 10

**Comment by AmrDeveloper** [comment]
Hello @Achisyg2,

Thanks for your report, 

`java.lang.ArrayIndexOutOfBoundsException: length=5; index=5 at`

Can you please provide some more information for example how many reactions you used? I think they are 5

what is the reaction index for the post that case the problem? try to print them in log before crash

**Comment by Achisyg2** [comment]
@AmrDeveloper I can't because after the error occurs one time then the app crashes every time I open it.

**Comment by AmrDeveloper** [comment]
@Achisyg2 This means your index is invalid, try to set the first reaction and scroll fast it will not crash, then try to check the firebase data and compare the index with number of reactions

**Comment by Achisyg2** [comment]
@AmrDeveloper I found the error. Some of the data stored in firestore return as null when I retrieve them. So, the library is working fine I think so. I'll let you know if something new happen.

**Comment by AmrDeveloper** [comment]
> @AmrDeveloper I found the error. Some of the data stored in firestore return as null when I retrieve them. So, the library is working fine I think so. I'll let you know if something new happen.

Okey, good luck bro :D
